spring.datasource.url=jdbc:postgresql://localhost:5432/checkupdb
spring.datasource.username=postgres
spring.datasource.password=KyrieIrving11
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

balldontlie.api.base-url=https://api.balldontlie.io/v1
balldontlie.api.key=75f21952-e11b-4e04-b2e1-ebcccc867c8a