spring.datasource.url=jdbc:postgresql://localhost:5432/checkupdb
spring.datasource.username=admin
spring.datasource.password=KyrieIrving11
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update